### PR TITLE
Drop container images from config/samples

### PR DESCRIPTION
**Pull request by dprince**
Jira: [OSP-30111](https://issues.redhat.com//browse/OSP-30111)

### CODE REVIEW

**Review by dkehn — APPROVED** [review]
lgtm

**Comment by beagles** [comment]
I ended up incorporating most of the fixes from this PR in the unbound resolver PR https://github.com/openstack-k8s-operators/designate-operator/pull/120 while trying to sort out why designate wasn't deploying. We can chat when you get back what the best course of action is.

**Pull request closed without merging**
