### PR TITLE
Standardize makefile

### PR DESCRIPTION
**Pull request by yazug**
cleanup DEFAULT_IMG and CONTROLLER_TOOLS_VERSION

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Review by fmount — APPROVED** [review]
Thanks!

**Comment by fmount** [comment]
It seems we might need to update the patch running both `go mod tidy` and `make manifests` [1].

[1] https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_designate-operator/47/pull-ci-openstack-k8s-operators-designate-operator-main-precommit-check/1654467160203857920/artifacts/test/build-log.txt

**Comment by yazug** [comment]
Looks like master is breaking with both of these last 2 patches one for make tidy as well as fixes for make golint

**Comment by yazug** [comment]
refreshed and included operator-sdk from local bin

**Comment by yazug** [comment]
Had to resolve a few trailing whitespace warnings from ci tests.

**Comment by dkehn** [comment]
All changes are there.

**Pull request closed without merging**
