### PR TITLE
Change Unbound deployment type to StatefulSet

### PR DESCRIPTION
**Pull request by omersch381**
Change Unbound deployment type to StatefulSet

### CODE REVIEW

**Comment by omersch381** [comment]
error: build error: Failed to push image: trying to reuse blob sha256:29291e31a76a7e560b9b7ad3cada56e8c18d50a96cca8a2573e4f4689d7aca77 at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout

**Comment by stuggi** [comment]
do we expect that designate is already used and also the cleanup of the current deployments need to be handled?

**Comment by omersch381** [comment]
Designate is still disabled by default in all of the CRs. It shouldn't be in use by anyone (yet).

**Pull request merged**
